# Generated by Django 3.2.6 on 2024-09-04 13:50

import blango_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blango_auth', '0002_auto_20240720_1105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blango_auth.models.BlangoUserManager()),
            ],
        ),
    ]
